---  
- hosts: localhost  
  gather_facts: no   
  vars:  
    region: us-east-1
    name: AWS-Demo
  tasks:  
    - name: get instance id
      command: aws ec2 describe-instances --filter Name=tag:Name,Values={{ name }} 
               --query 'Reservations[0].Instances[0].InstanceId' --output text
      register: instanceid

    - name: stop instance 
      ec2:  
        region: "{{ region }}"
        instance_ids: "{{ instanceid.stdout }}"  
        state: stopped
        wait: yes
      when: instanceid.stdout!="None"
