---
- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    region: us-east-1e
    name: RHEL-1
  tasks:
    - name: get instance id
      instance_lookup:
        region: "{{ region }}"
        tags:
          Name: "{{ name }}"
      register: instanceid

    - debug: var=instanceid.instance_ids

    - name: stoped instance
      ec2:
        region: "{{ region }}"
        instance_ids: "{{ instanceid.instance_ids }}"
        state: stoped
        wait: yes
      when: instanceid is defined
