---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: all   
  tasks:  
    - name: terminate instances
      ec2:
        region: "{{ region }}"  
        wait: yes  
        instance_ids: ['i-0828c0b0f6eb50b7b', 'i-0ded0ade6510c6ff1']  
        state: absent  
